### ISSUE TITLE
How does reducer state data relate to a template?

### ISSUE THREAD

**Issue by chrisabrams** [littlstar/stardux#5]
if I had a reducer:

```
(state, action) => {return {foo: 'bar'}}
```

How do I get access to `foo` in the template?

**Comment by chrisabrams** [comment]
How can I get the current state, and change a value of `foo` in a template, based on what the state is?

I'm struggling to figure out how I can use reducers to help get state data into a template. If this is not the use case for reducers, then what are reducers used for?

The redux documentation makes it seem that reducers are used to reduce down the current state.

**Comment by chrisabrams** [comment]
It looks like the default is that `.update()` is [patching the container](https://github.com/littlstar/stardux/blob/e65c2f4ec22c20b29417dfcb7653e6bfeff96a70/src/index.js#L363) in the root reducer.

Since you can't call `.update()` inside a reducer, how does one update the [container state data](https://github.com/littlstar/stardux/blob/e65c2f4ec22c20b29417dfcb7653e6bfeff96a70/src/index.js#L364) when the reducer is called?

**Comment by jwerle** [comment]
@chrisabrams I've been looking at the code and the expected functionality above is not occurring :( This is a bug

**Comment by jwerle** [comment]
`...reducers` should be before the `createRootReducer(this)` considering the root reducer is where the update occurs

**Comment by chrisabrams** [comment]
Ah ok, so I'm not completely lost :o

I started digging into the code myself, but I'm not sure exactly where to go. Very excited to see a fix and how to do this :)

**Comment by chrisabrams** [comment]
I tried changing the order but that didn't help.

**Comment by jwerle** [comment]
@chrisabrams I'm working on a fix and will hopefully have a PR soon

**Comment by chrisabrams** [comment]
@jwerle Awesome :)

**Comment by chrisabrams** [comment]
@jwerle any thoughts on this? Is there a direction I can look into to help?

**Comment by jwerle** [comment]
hey @chrisabrams, sorry I've been stupid busy. https://github.com/littlstar/stardux/commit/b7853acc7ab7b9755086083a2f98c262c4885e0d fixes this issue. Passing reducers to the `Container` constructor or to the `createContainer()` function works as expected. State is reduced before an update occurs to the view.

**Comment by jwerle** [comment]
@chrisabrams i've added you as a collaborator on the project. Let me know if this issue is fixed so I can close!

**Comment by chrisabrams** [comment]
Yes, issue has been fixed. I'm going to take your gist and make an example on the project.
